#!/bin/sh

#export QT_QPA_PLATFORMTHEME=qt5ct
#xautolock -time 10 -locker slock &
xsetroot -cursor_name left_ptr
pgrep -x ssh-agent > /dev/null || eval "$(ssh-agent -s)"
exec dbus-launch --sh-syntax --exit-with-session bspwm
