#! /bin/sh
# _
#| |__  ___ _ ____      ___ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_|

# Clear previous rules
bspc rule -r "*"

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nm-applet > /dev/null || nm-applet &
launch_polybar &
feh --bg-scale /home/vntasis/.config/wallpaper &
pgrep -x picom > /dev/null || picom &
light -I &
pgrep -x btops > /dev/null || btops &

# Declare monitors and desktops
pgrep -x btops > /dev/null || \
    { bspc monitor LVDS-1 -d  1 2 3 4 5 && \
        bspc monitor VGA-1 -d 6 7 8 9 10; }

# Global settings
bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child

bspc config pointer_modifier            shift
bspc config focus_follows_pointer       true

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config border_width                3
bspc config window_gap                  8
bspc config bottom_padding              10
bspc config bottom_monocle_padding      5

bspc config focused_border_color        "#007cce"
bspc config presel_feedback_color       "#282a36"

bspc config split_ratio                 0.52
bspc config borderless_monocle          false
bspc config gapless_monocle             true


# Rules
bspc rule -a '*:*:calc' state=floating
bspc rule -a 'mpv:video0' state=floating sticky=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
